### ISSUE TITLE
How does many optional options design when use camel components in kamelets

### ISSUE THREAD

**Issue by wingerx** [apache/camel-kamelets#467]
Hey,
Could anyone help me?
I created Kameletbinding for DBZ component by kamelets developer guide.But i want to configure only the required options, and the optional options are filled in as needed in kamelets binding yaml file. There are so many options for DBZ, and it is not conducive to subsequent expansion if all are defined. 
There is an [additionalProperties](https://camel.apache.org/components/latest/debezium-mysql-component.html#_component_options) option in DBZ components, but I don’t know how to configure it in yaml and make it take effect.

Any ideas?

**Comment by wingerx** [comment]
I'm sorry,i don't understand.
Can you explain this for me please?

**Comment by oscerd** [comment]
In camel component you have multiple parameters to tune your route and set everything. A Kamelet needs to define just a subset of the options to perform a pre-defined operation. So in a Kamelet you'll never see all the possible options listed and configurabile, because in terms of Kamelets this is conceptually wrong.

**Comment by wingerx** [comment]
ok, I see.
Thanks a lot. @oscerd
