### ISSUE TITLE
override example template for these action kamelets

### ISSUE THREAD

**Issue by MelissaFlinn** [apache/camel-kamelets#866]
By default, the Kamelets template auto generates examples. We discovered that the auto-generated examples for the following Kamelets do not work. (As a workaround, we provided working examples in the Kamelets Reference document.)
avro-deserialize-action-binding.yaml
avro-serialize-action.kamelet.yaml
has-header-filter-action.kamelet.yaml
insert-action.kamelet.yaml
protobuf-deserialize-action.kamelet.yaml
protobuf-deserialize-action.kamelet.yaml

**Comment by oscerd** [comment]
This is a description not really complete. What is wrong exactly?

**Comment by squakez** [comment]
If I understand correctly, the template we use to render Kamelets documentation is not correct for action kind Kamelets.

**Comment by oscerd** [comment]
The reported list is just a subset, so only this subset has something wrong, but what is it? Waiting for clarification.

**Comment by MelissaFlinn** [comment]
What is wrong: the auto-generated examples for those Kamelets do not work.

**Comment by MelissaFlinn** [comment]
The examples need additional steps - such as adding a serialize/deserialize step. The way that the template generates examples now, we cannot override the generated ones to provide examples that are correct/useful.

**Comment by oscerd** [comment]
Now I have a description.

**Comment by claudio4j** [comment]
I am investigating this issue. Looking at the [avro-deserialize-action](https://camel.apache.org/camel-kamelets/next/avro-deserialize-action.html) and the corresponding binding example file [avro-deserialize-action-binding.yaml](https://github.com/apache/camel-kamelets/blob/0.7.x/templates/bindings/camel-k/avro-deserialize-action-binding.yaml)

It fails with `JsonParseException: Needed to read 36 bytes, missed 36 before end-of-input`

The kamelet binding should be fixed by having a json message in the timer and additional steps to convert string -> json -> avro.

I had not run all the other auto generated kamelet biding to see if they work. 

To fix this, I propose one of the following options:
1. Have all the kamelet bindings in `templates/bindings/camel-k` directory in working condition and have `docs/modules/ROOT/examples/js/kamelets.js` to source these files as examples instead to auto generate them. And have only one kafka or knative channel sink in the example binding file.

2. Fix only the non working binding example files in `templates/bindings/camel-k` directory, add a comment marker to it, and change `docs/modules/ROOT/examples/js/kamelets.js` to source this example file into the generated html doc, instead to auto generated the binding example.
